import {
  EnrolledCourse,
  Certificate,
  WishlistItem,
  UserProfile,
  Activity,
  DashboardStats,
} from "@/types/dashboard";

export const mockUserProfile: UserProfile = {
  id: "1",
  name: "Rafiq Ahmed",
  email: "rafiq@example.com",
  phone: "+880 1712-345678",
  avatar: "/avatars/rafiq.jpg",
  bio: "Full-stack developer passionate about React and Node.js. Currently learning system design and cloud architecture.",
  location: "Dhaka, Bangladesh",
  website: "https://rafiq.dev",
  joinedAt: "2024-06-15",
  role: "student",
};

export const mockEnrolledCourses: EnrolledCourse[] = [
  {
    id: "1",
    title: "Complete React & Next.js Developer",
    slug: "complete-react-nextjs-developer",
    description: "Master React 19 and Next.js 15 from zero to hero.",
    longDescription: "",
    category: "Web Development",
    level: "Intermediate",
    price: 79.99,
    thumbnail: "/images/courses/react-nextjs.jpg",
    rating: 4.8,
    reviewCount: 2340,
    enrolledCount: 12500,
    duration: "42 hours",
    lectures: 186,
    instructor: { name: "Michael Chen", avatar: "/avatars/michael.jpg" },
    updatedAt: "2025-12-01",
    enrolledAt: "2025-09-15",
    progress: 72,
    lastAccessedAt: "2026-07-14",
    completedLectures: 134,
    currentLecture: 135,
  },
  {
    id: "2",
    title: "Advanced TypeScript Masterclass",
    slug: "advanced-typescript-masterclass",
    description: "Deep dive into TypeScript generics, decorators, and advanced patterns.",
    longDescription: "",
    category: "Web Development",
    level: "Advanced",
    price: 59.99,
    thumbnail: "/images/courses/typescript.jpg",
    rating: 4.9,
    reviewCount: 890,
    enrolledCount: 5200,
    duration: "28 hours",
    lectures: 120,
    instructor: { name: "Sarah Johnson", avatar: "/avatars/sarah.jpg" },
    updatedAt: "2025-11-20",
    enrolledAt: "2025-11-01",
    progress: 100,
    lastAccessedAt: "2026-06-28",
    completedLectures: 120,
    currentLecture: 120,
  },
  {
    id: "3",
    title: "Python for Data Science & ML",
    slug: "python-data-science-ml",
    description: "Learn Python, Pandas, NumPy, Scikit-learn, and TensorFlow.",
    longDescription: "",
    category: "Data Science",
    level: "Beginner",
    price: 89.99,
    thumbnail: "/images/courses/python-ds.jpg",
    rating: 4.7,
    reviewCount: 3100,
    enrolledCount: 18900,
    duration: "56 hours",
    lectures: 240,
    instructor: { name: "David Brown", avatar: "/avatars/david.jpg" },
    updatedAt: "2026-01-10",
    enrolledAt: "2026-01-20",
    progress: 35,
    lastAccessedAt: "2026-07-12",
    completedLectures: 84,
    currentLecture: 85,
  },
  {
    id: "4",
    title: "UI/UX Design Fundamentals",
    slug: "uiux-design-fundamentals",
    description: "Design beautiful, user-friendly interfaces from scratch.",
    longDescription: "",
    category: "UI/UX Design",
    level: "Beginner",
    price: 49.99,
    thumbnail: "/images/courses/uiux.jpg",
    rating: 4.6,
    reviewCount: 1560,
    enrolledCount: 8700,
    duration: "20 hours",
    lectures: 88,
    instructor: { name: "Emily Davis", avatar: "/avatars/emily.jpg" },
    updatedAt: "2025-10-05",
    enrolledAt: "2026-03-01",
    progress: 15,
    lastAccessedAt: "2026-07-10",
    completedLectures: 13,
    currentLecture: 14,
  },
  {
    id: "5",
    title: "Docker & Kubernetes Bootcamp",
    slug: "docker-kubernetes-bootcamp",
    description: "Master containerization and orchestration for production.",
    longDescription: "",
    category: "DevOps",
    level: "Intermediate",
    price: 69.99,
    thumbnail: "/images/courses/docker-k8s.jpg",
    rating: 4.8,
    reviewCount: 720,
    enrolledCount: 4100,
    duration: "32 hours",
    lectures: 140,
    instructor: { name: "Farhana Akter", avatar: "/avatars/farhana.jpg" },
    updatedAt: "2025-12-15",
    enrolledAt: "2026-05-10",
    progress: 0,
    lastAccessedAt: "2026-05-10",
    completedLectures: 0,
    currentLecture: 1,
  },
];

export const mockCertificates: Certificate[] = [
  {
    id: "cert-1",
    courseId: "2",
    courseTitle: "Advanced TypeScript Masterclass",
    completedAt: "2026-06-28",
    certificateUrl: "/certificates/cert-1.pdf",
    instructor: "Sarah Johnson",
  },
];

export const mockWishlist: WishlistItem[] = [
  {
    id: "wish-1",
    course: {
      id: "6",
      title: "Node.js Microservices Architecture",
      slug: "nodejs-microservices",
      description: "Build scalable microservices with Node.js, Docker, and gRPC.",
      longDescription: "",
      category: "Web Development",
      level: "Advanced",
      price: 99.99,
      thumbnail: "/images/courses/microservices.jpg",
      rating: 4.9,
      reviewCount: 450,
      enrolledCount: 2800,
      duration: "38 hours",
      lectures: 160,
      instructor: { name: "Michael Chen", avatar: "/avatars/michael.jpg" },
      updatedAt: "2026-02-01",
    },
    addedAt: "2026-07-01",
  },
  {
    id: "wish-2",
    course: {
      id: "7",
      title: "AWS Solutions Architect",
      slug: "aws-solutions-architect",
      description: "Prepare for the AWS Solutions Architect certification.",
      longDescription: "",
      category: "Cloud Computing",
      level: "Intermediate",
      price: 109.99,
      thumbnail: "/images/courses/aws.jpg",
      rating: 4.7,
      reviewCount: 1200,
      enrolledCount: 7500,
      duration: "45 hours",
      lectures: 200,
      instructor: { name: "Farhana Akter", avatar: "/avatars/farhana.jpg" },
      updatedAt: "2026-03-15",
    },
    addedAt: "2026-07-05",
  },
];

export const mockActivity: Activity[] = [
  {
    id: "act-1",
    type: "course_progress",
    title: "Continued React & Next.js Developer",
    description: "Completed 3 lectures in Module 12: Server Components",
    date: "2026-07-14",
    courseId: "1",
  },
  {
    id: "act-2",
    type: "course_progress",
    title: "Progressed in Python for Data Science",
    description: "Completed 2 lectures in Module 5: Pandas DataFrames",
    date: "2026-07-12",
    courseId: "3",
  },
  {
    id: "act-3",
    type: "wishlist",
    title: "Added course to wishlist",
    description: "Added AWS Solutions Architect to your wishlist",
    date: "2026-07-05",
  },
  {
    id: "act-4",
    type: "course_progress",
    title: "Started UI/UX Design Fundamentals",
    description: "Began Module 1: Design Thinking Process",
    date: "2026-07-10",
    courseId: "4",
  },
  {
    id: "act-5",
    type: "certificate",
    title: "Certificate earned!",
    description: "You completed Advanced TypeScript Masterclass",
    date: "2026-06-28",
    courseId: "2",
  },
];

export const mockDashboardStats: DashboardStats = {
  enrolledCourses: 5,
  completedCourses: 1,
  certificates: 1,
  totalSpent: 349.95,
  hoursLearned: 86,
};
